name: Password Notify Test

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: "https://pyopdfzwpwpoeqgvaaew.supabase.co"
      SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b3BkZnp3cHdwb2VxZ3ZhYWV3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjM1Njg4MCwiZXhwIjoyMDcxOTMyODgwfQ.8_0HTmF62eBNP4fc9UKAtTWvWVz9KO-bvlS6xed0xPc"
      LINE_CHANNEL_ACCESS_TOKEN: "HRAyhm11r07e+/7oFOVUdFVLrxvQ4EZdrVv+0fUKOlZWtsfC36badvaP4WntaulV/DDJ/+TRtzv60KNFYGpcKNxwr0Vslzawt+oWc+sRLnNqBBPk5X/9Jkj1L1m+1uL7abh63X/V6RtR9TX4UTtf/QdB04t89/1O/w1cDnyilFU="
      LINE_USER_ID: "U7259acbe9a828eabbd75822a8cabdd8c"
      ADMIN_PASSWORD: "naoki2480"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run auth.py
        run: python auth.py
