SUPABASE_URL = "https://pyopdfzwpwpoeqgvaaew.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b3BkZnp3cHdwb2VxZ3ZhYWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTY4ODAsImV4cCI6MjA3MTkzMjg4MH0.HRsY6OSBEH6GQK0AonFjTH4TbgfwCbaAOzpR1o2pO2k"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b3BkZnp3cHdwb2VxZ3ZhYWV3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjM1Njg4MCwiZXhwIjoyMDcxOTMyODgwfQ.8_0HTmF62eBNP4fc9UKAtTWvWVz9KO-bvlS6xed0xPc"
SUPABASE_SCHEMA = "public"

SUPABASE_TABLE_PROFILES = "client_profiles"
SUPABASE_TABLE_RECORDS  = "client_portal_records"
SUPABASE_TABLE_EVENTS   = "client_portal_events"

BASE_URL = "https://naokifp.streamlit.app"

[postgres]
user = "postgres"
password = "WkmnNaqE9VV6._D"
host = "pyopdfzwpwpoeqgvaaew.aws-0-ap-northeast-1.pooler.supabase.com"
port = 6543
database = "postgres"
sslmode = "require"

LINE_CHANNEL_ACCESS_TOKEN = "d8GGvrVrPPEmtxL3sowUPHNmza77gKSFjki7cj53pv0V1F0FBgBoYktuMhG3mUBm/DDJ/+TRtzv60KNFYGpcKNxwr0Vslzawt+oWc+sRLnNRpYmZeyd8nqMooruhVcf8NPinXLyBS9q1qKB2NvcTzgdB04t89/1O/w1cDnyilFU="
LINE_USER_ID = "U7259acbe9a828eabbd75822a8cabdd8c"
