SUPABASE_URL = "https://pyopdfzwpwpoeqgvaaew.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b3BkZnp3cHdwb2VxZ3ZhYWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTY4ODAsImV4cCI6MjA3MTkzMjg4MH0.HRsY6OSBEH6GQK0AonFjTH4TbgfwCbaAOzpR1o2pO2k"
SUPABASE_SCHEMA = "public"

SUPABASE_TABLE_PROFILES = "client_profiles"
SUPABASE_TABLE_RECORDS  = "client_portal_records"
SUPABASE_TABLE_EVENTS   = "client_portal_events"

BASE_URL = "https://naokifp.streamlit.app"

[postgres]
user = "postgres.pyopdfzwpwpoeqgvaaew"
password = "WkmnNaqE9VV6._D"
host = "aws-0-ap-northeast-1.pooler.supabase.com"
port = 6543
database = "postgres"
sslmode = "require"
